/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2025-11-17 08:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.users_005fboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/view/users_board/../inc/footer.jsp", Long.valueOf(1763364102616L));
    _jspx_dependants.put("/view/users_board/../inc/header.jsp", Long.valueOf(1763367970915L));
    _jspx_dependants.put("jar:file:/D:/jeongmin/jeongmin001/track003_java/Servers/Tomcat%20v9.0%20Server%20at%20localhost-config/apache-tomcat-9.0.46/wtpwebapps/ex006/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1762995609777L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap 5 Website Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"ttpss://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  .fakeimg {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    background: #aaa;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"p-5 bg-primary text-white text-center\">\r\n");
      out.write("  <h1>MBTI Quest Board</h1>\r\n");
      out.write("  <p>각종 보드들의 기능익히기 - PAGING + UPLOAD + BOARD</p> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-dark navbar-dark\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <ul class=\"navbar-nav\"> \r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	        <a class=\"nav-link\" href=\"\">로그아웃</a>\r\n");
      out.write("	      </li>   \r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	        <a class=\"nav-link\" href=\"\">LOGIN</a>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	        <a class=\"nav-link\" href=\"\">JOIN</a>\r\n");
      out.write("	      </li>    \r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	        <a class=\"nav-link\" href=\"\">Quest Board</a>\r\n");
      out.write("	      </li>  \r\n");
      out.write("    </ul> \r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- 	header		 -->\r\n");
      out.write("<!-- 	header		 -->\r\n");
      out.write("<!-- 	header		 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	let result = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	\r\n");
      out.write("	if(result == '비밀번호를 확인해주세요'){alert(result); history.go(-1);}\r\n");
      out.write("	else if(result.length !=0){alert(result); } \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 	header		 --> \r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("	<h3>WELCOME! 회원가입</h3>\r\n");
      out.write("	<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join.users\"  method=\"post\">\r\n");
      out.write("		<div class=\"mb-3 mt-3\">\r\n");
      out.write("			<label  for=\"email\" class=\"form-label\">Email:</label> \r\n");
      out.write("			<input  type=\"email\" class=\"form-control\" id=\"email\"\r\n");
      out.write("					placeholder=\"이메일을 입력해주세요\" required  name=\"email\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<label for=\"password\" class=\"form-label\">Password:</label> \r\n");
      out.write("			<input type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("					placeholder=\"비밀번호를 입력해주세요\" name=\"password\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("			<label class=\"form-check-label\"  for=\"mbti\">MBTI TYPE : </label>  \r\n");
      out.write("			<select   name=\"mbtitypeid\"  id=\"mbti\"  class=\"form-control\">\r\n");
      out.write("				<option value=\"1\">ISTJ</option>\r\n");
      out.write("				<option value=\"2\">ISFJ</option>\r\n");
      out.write("				<option value=\"3\">INFJ</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3 text-end\">\r\n");
      out.write("		<button type=\"submit\" class=\"btn btn-primary\">회원가입</button>\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.users\"  class=\"btn btn-primary\">회원가입</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		 \r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ctrl + shift + f -->\r\n");
      out.write("<!-- 	footer		 --> \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- 	footer		 -->\r\n");
      out.write("<!-- 	footer		 -->\r\n");
      out.write("<!-- 	footer		 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"mt-5 p-4 bg-dark text-white text-center\">\r\n");
      out.write("  <p>Footer</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!-- 				\r\n");
      out.write("	action=\"join_process.jsp\"\r\n");
      out.write("	method=\"post\"\r\n");
      out.write("	name=\"email\"   name=\"password\"  name=\"mbti_type_id\" \r\n");
      out.write("-->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
